function [cp_tot, cna_tot, aero_sections] = get_aerodynamics(sections, M, alpha, R_ref)

num_sections = numel(sections);
aero_section_idx = 1;
aero_sections = {};

x_start = 0;

for section_idx = 1:num_sections
    section = sections{section_idx};

    section.x = section.x - x_start;
    if (isfield(section,'subcomponents') && ((isfield(section.subcomponents, 'trapezoidfinset') || isfield(section.subcomponents, 'freeformfinset'))))
        subcomponents = section.subcomponents;
        if isfield(subcomponents, 'trapezoidfinset')
            finset = section.subcomponents.trapezoidfinset;

            fins = struct( ...
                'cr',     finset.rootchord, ...
                'ct',     finset.tipchord, ...
                'xr',     finset.sweeplength, ...
                's',      finset.height, ...
                'R_body', section.forerad, ...
                'R_ref',  R_ref, ...
                'n_fins', finset.fincount);

            CNa_fins = calc_CNa_fins(fins, M, alpha);
            Cp_fins  = calc_CP_fins (fins, M);

            Cp_fins = Cp_fins + section.x + finset.axialoffset.Text;
            x_pos = section.x + finset.axialoffset.Text;

            if strcmp(finset.axialoffset.method, 'bottom')
                Cp_fins = Cp_fins  + section.length - finset.rootchord;
                x_pos = x_pos + section.length - finset.rootchord;
            end


            aero_sections{aero_section_idx} = struct( ...
                'CNa', CNa_fins, ...
                'Cp', Cp_fins, ...
                'name', finset.name, ...
                'id', finset.id, ...
                'x', x_pos, ...
                'length', finset.rootchord, ...
                'd', 0, ...
                'D', inf);
            aero_section_idx = aero_section_idx + 1;

        elseif isfield(subcomponents, 'freeformfinset')
            finset = section.subcomponents.freeformfinset;
            points = [finset.finpoints.point{:}];
            fins = struct( ...
                'xPt', [points.x], ...
                'yPt', [points.y], ...
                'R_body', section.forerad, ...
                'R_ref',  R_ref, ...
                'n_fins', finset.fincount);

            CNa_fins = calc_CNa_fins(fins, M, alpha);
            Cp_fins  = calc_CP_fins (fins, M);

            Cp_fins = Cp_fins + section.x + finset.axialoffset.Text;
            x_pos = section.x + finset.axialoffset.Text;

            if strcmp(finset.axialoffset.method, 'bottom')
                Cp_fins = Cp_fins  + section.length - tail([points.x]',1);
                x_pos = x_pos + section.length - tail([points.x]',1);
            end


            aero_sections{aero_section_idx} = struct( ...
                'CNa', CNa_fins, ...
                'Cp', Cp_fins, ...
                'name', finset.name, ...
                'id', finset.id, ...
                'x', x_pos, ...
                'length', tail([points.x]',1), ...
                'd', 0, ...
                'D', inf);
            aero_section_idx = aero_section_idx + 1;
        end
    end
    if section.aftrad == section.forerad
        % Body Tube
        CNa = calc_CNa_bodytube(section.aftrad, section.length, R_ref,     alpha);
        Cp  = calc_CP_bodytube (section.length, section.aftrad, section.x, alpha) + section.x;

        aero_sections{aero_section_idx} = struct( ...
            'CNa', CNa, ...
            'Cp', Cp, ...
            'name', section.name, ...
            'id', section.id, ...
            'x', section.x, ...
            'length', section.length, ...
            'd', section.inner_radius*2, ...
            'D', section.forerad*2);

        aero_section_idx = aero_section_idx + 1;

    elseif section.forerad == 0
        % Nosecone
        CNa_nose = calc_CNa_ogive(section.aftrad, section.length, R_ref, alpha, M);
        Cp_nose  = calc_CP_ogive (section.length, section.aftrad, R_ref, alpha, M);

        aero_sections{aero_section_idx} = struct( ...
            'CNa', CNa_nose, ...
            'Cp', Cp_nose, ...
            'name', section.name, ...
            'id', section.id, ...
            'x', section.x, ...
            'length', section.length);

        aero_section_idx = aero_section_idx + 1;

    elseif section.forerad < section.aftrad
        CNa = calc_CNa_shoulder(section.forerad, section.aftrad, R_ref);
        Cp  = calc_CP_shoulder (section.forerad, section.aftrad, section.length, section.x, alpha);

        aero_sections{aero_section_idx} = struct( ...
            'CNa', CNa, ...
            'Cp', Cp, ...
            'name', section.name, ...
            'id', section.id, ...
            'x', section.x, ...
            'length', section.length, ...
            'd', 0, ...
            'D', inf);

        aero_section_idx = aero_section_idx + 1;

    elseif section.forerad > section.aftrad
        CNa = calc_CNa_boattail(section.forerad, section.aftrad, section.length, R_ref, M);
        Cp  = calc_CP_boattail (section.forerad, section.aftrad, section.length) + section.x;

        aero_sections{aero_section_idx} = struct( ...
            'CNa', CNa, ...
            'Cp', Cp, ...
            'name', section.name, ...
            'id', section.id, ...
            'x', section.x, ...
            'length', section.length, ...
            'd', section.aftrad*2, ...
            'D', section.outer_radius*2);
        aero_section_idx = aero_section_idx + 1;
    end
end

num_aero_sections = aero_section_idx - 1;

cp_tot = 0;
cna_tot = 0;

for n = 1:num_aero_sections

    section = aero_sections{n};
    CNa = section.CNa;
    Cp  = section.Cp;

    cp_tot = cp_tot  + Cp*CNa;
    cna_tot = cna_tot +    CNa;
end

cp_tot  = cp_tot / cna_tot;
end