function [sections] = load_sections(ork)

sections = {};
section_idx = 1;

x_pos = 0;

for i = 1:size(ork,2)

    name = ork(i).Type;
    comp = ork(i).Data;
    material = comp.material.Text;
    length = comp.length;

    if isfield(comp,'subcomponents')
        subcomp = comp.subcomponents;
    else
        subcomp = 'missing';
    end

    if strcmp(name, 'nosecone')
        aftrad = remove_auto(comp.aftradius);

        sections{section_idx} = struct( ...
            'x', x_pos, ...
            'length', length, ...
            'forerad', 0, ...
            'aftrad', aftrad, ...
            'material', material, ...
            'name', comp.name, ...
            'id', comp.id);
        section_idx = section_idx + 1;

        x_pos = x_pos + length;
    end

    if strcmp(name, 'bodytube')
        rad = remove_auto(comp.radius);

        sections{section_idx} = struct( ...
            'x', x_pos, ...
            'length', length, ...
            'forerad', rad, ...
            'aftrad', rad, ...
            'material', material, ...
            'name', comp.name, ...
            'subcomponents', subcomp, ...
            'id', comp.id, ...
            'inner_radius', rad - comp.thickness);
        section_idx = section_idx + 1;

        x_pos = x_pos + length;
    end

    if strcmp(name, 'transition')
        forerad = remove_auto(comp.foreradius);
        aftrad = remove_auto(comp.aftradius);

        if isfield(comp, 'subcomponents')
           subcomp = comp.subcomponents;
        else
           subcomp = missing;
        end

        sections{section_idx} = struct( ...
            'x', x_pos, ...
            'length', length, ...
            'forerad', forerad, ...
            'aftrad', aftrad, ...
            'material', material, ...
            'name', comp.name, ...
            'id', comp.id, ...
            'outer_radius', min(forerad, aftrad) + comp.thickness, ...
            'subcomponents', subcomp);
        x_pos = x_pos + length;
        section_idx = section_idx + 1;
    end
end
end